# Arrays
* pip install array or pip3 install array
## Type conda prompt

In [72]:
import array as ar

In [32]:
a=ar.array('i',[5,3,1,7,4])
b=ar.array('i',[7,3,4,2])

In [33]:
a                                   #To Display the elements 

array('i', [5, 3, 1, 7, 4])

In [34]:
b

array('i', [7, 3, 4, 2])

In [35]:
len(a)                            #To know (or) display length

5

In [36]:
len(b)

4

In [37]:
a[0]                             #To know the particular element (slicing)

5

In [38]:
b[0]

7

In [39]:
a[0:]

array('i', [5, 3, 1, 7, 4])

In [40]:
b[0:]

array('i', [7, 3, 4, 2])

In [41]:
a[1:]

array('i', [3, 1, 7, 4])

In [42]:
b[1:]

array('i', [3, 4, 2])

In [43]:
a[::-1]                         #To print elements in reverse order

array('i', [4, 7, 1, 3, 5])

In [44]:
b[::-1]

array('i', [2, 4, 3, 7])

In [45]:
a.append(1)                    #To add the elements in an array (append will add elements at last)

In [46]:
a

array('i', [5, 3, 1, 7, 4, 1])

In [48]:
b.append(8)

In [49]:
b

array('i', [7, 3, 4, 2, 8])

In [50]:
a.insert(3,9)               #To insert the elements in an array (by using this we can add element at any position)

In [51]:
a

array('i', [5, 3, 1, 9, 7, 4, 1])

In [52]:
b.insert(6,0)

In [53]:
b

array('i', [7, 3, 4, 2, 8, 0])

In [54]:
b.insert(7,5)

In [55]:
b

array('i', [7, 3, 4, 2, 8, 0, 5])

In [56]:
a+b                         #Concatenation

array('i', [5, 3, 1, 9, 7, 4, 1, 7, 3, 4, 2, 8, 0, 5])

In [57]:
a.pop()                 #Pop will remove the element from an array(as it is empty it will pop element which is at last)

1

In [58]:
a.pop(3)        #Pop will remove the element from an array(as we given one index it will remove that element from an array)

9

In [59]:
a.remove(3)     #Remove option will directly remove the element we given,it will not consider index

In [60]:
a

array('i', [5, 1, 7, 4])

In [62]:
b.pop(2)

4

In [63]:
a

array('i', [5, 1, 7, 4])

In [65]:
for i in a:print(i)

5
1
7
4


In [66]:
for i in b:print(i)

7
3
2
8
0
5


# Numpy
pip3 install numpy

In [74]:
import numpy as np

In [85]:
r=np.array([(4,3,2),(3,7,8)])
p=np.array([(1,2,3),(2,5,6)])

In [86]:
r

array([[4, 3, 2],
       [3, 7, 8]])

In [87]:
p

array([[1, 2, 3],
       [2, 5, 6]])

In [88]:
r.ndim                 #To check the dimensions

2

In [89]:
p.itemsize              #To check the size of item(it depends on compiler)

4

In [90]:
r.itemsize

4

In [91]:
r.dtype               #To check the data type(it depends on system i.e.laptop)

dtype('int32')

In [92]:
r.size               # Number of elements

6

In [93]:
p.size

6

In [94]:
r.shape             #Number of rows and columns

(2, 3)

In [95]:
r.reshape(3,2)      #it will change the 2*3 to 3*2

array([[4, 3],
       [2, 3],
       [7, 8]])

In [96]:
r.min()           # Dispalys minimum value

2

In [97]:
p.max()         #Displays maximum value

6

In [98]:
r.sum()        #Total sum of the elements

27

In [99]:
p.sum()

19

In [100]:
r

array([[4, 3, 2],
       [3, 7, 8]])

In [101]:
r.sum(axis=0)      #Sum in column wise

array([ 7, 10, 10])

In [102]:
r.sum(axis=1)      #Sum in row wise

array([ 9, 18])

In [105]:
p

array([[1, 2, 3],
       [2, 5, 6]])

In [106]:
p.sum(axis=0)

array([3, 7, 9])

In [107]:
p.sum(axis=1)

array([ 6, 13])

In [108]:
#slicing (it will the display element according to index)
r[0,2]

2

In [110]:
p[1,1]

5

In [111]:
r[0:2,1]     #It means the middle index from either sides of row index

array([3, 7])

In [112]:
r[0:,1]     #It means from all the rows extracting the index of 1

array([3, 7])

In [113]:
r[0:,2]

array([2, 8])

In [114]:
r

array([[4, 3, 2],
       [3, 7, 8]])

In [116]:
r[r>2]       #All the elements greater then the 2 is displayed

array([4, 3, 3, 7, 8])

In [117]:
r.sort()     #In each and every row sorting will be done

In [118]:
r

array([[2, 3, 4],
       [3, 7, 8]])

In [119]:
p.sort()

In [120]:
p

array([[1, 2, 3],
       [2, 5, 6]])

In [121]:
r+p          #Addition of elements will be done with correspondin rows

array([[ 3,  5,  7],
       [ 5, 12, 14]])

In [122]:
r*p           #Multiplication

array([[ 2,  6, 12],
       [ 6, 35, 48]])

In [123]:
r/p           #Divison

array([[2.        , 1.5       , 1.33333333],
       [1.5       , 1.4       , 1.33333333]])

In [124]:
r%p           #Mod

array([[0, 1, 1],
       [1, 2, 2]], dtype=int32)

In [125]:
r-p           #Subraction

array([[1, 1, 1],
       [1, 2, 2]])

In [126]:
np.vstack((r,p))  #Concatinate in vertical manner

array([[2, 3, 4],
       [3, 7, 8],
       [1, 2, 3],
       [2, 5, 6]])

In [127]:
np.hstack((r,p))      #Concatinate in horizontal manner

array([[2, 3, 4, 1, 2, 3],
       [3, 7, 8, 2, 5, 6]])

In [128]:
np.sqrt(r)    #Square root

array([[1.41421356, 1.73205081, 2.        ],
       [1.73205081, 2.64575131, 2.82842712]])

In [129]:
np.sqrt(p)       #Square root

array([[1.        , 1.41421356, 1.73205081],
       [1.41421356, 2.23606798, 2.44948974]])

In [130]:
np.std(r)        #Standard deviation

2.217355782608345

In [131]:
np.mean(p)       #Mean

3.1666666666666665